### ISSUE TITLE
Extending default routes don't work

### ISSUE THREAD

**Issue by legendtang** [17koa/koa-generator#27]
``` js
router.get('/', async function(ctx, next) {
    ctx.state = {
        title: 'koa2 title'
    };

    await ctx.render('index', {});
})

router.get('/test', async function(ctx, next) {
    let data = {a:1, b:2}
    ctx.status = 200;
    ctx.body = data;
    await next();
});

// -> /test - 404
```

Do I made any mistakes? Thanks.

**Comment by sinalvee** [comment]
Because there is `router.use('/', index.routes(), index.allowedMethods());` in `app.js`.
When you wtrit `router.get('/test', ...)`, the router becomes `//test`, so `/test` got `404`
You can change to `router.get('test', ...)`,

**Comment by legendtang** [comment]
@sinalvee Yes, I found out that `Koa` routes behave differently comparing to `Express`. I think the generated code is quite misleading. Root route is actually '//' and user route is actually '/user/', which coincidentally behaves the same as '/'  and '/user'. Your generator does confuse many newbies like me and even a Koa user.

So, would you like to improve your example code or just add some comment on it?
