### ISSUE TITLE
Deprecated use of generators

### ISSUE THREAD

**Issue by kristianmandrup** [17koa/koa-generator#31]
`$ ./bin/run`

```
koa deprecated Support for generators will been removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/tree/v2.x#old-signature-middleware-v1x app.js:23:5
```

**Comment by libertyAlone** [comment]
wrap koa-static with koa-convert like this:

`
app.use(convert(require('koa-static')(__dirname + '/public')));
`

**Comment by tomoat** [comment]
![image](https://cloud.githubusercontent.com/assets/7428698/20027251/e598bb00-a349-11e6-9a49-91f542473a7a.png)

![image](https://cloud.githubusercontent.com/assets/7428698/20027262/18ab0d9a-a34a-11e6-8ac2-0403b9c3490d.png)
