### ISSUE TITLE
koa2 --ejs

### ISSUE THREAD

**Issue by i5ting** [17koa/koa-generator#37]
请您确认一个 bug，我执行命令：

koa2 --ejs

生成的代码中仍然使用 jade

app.use(views(__dirname + '/views', {
  extension: 'jade'
}));

**Comment by glennWang** [comment]
狼哥，mac os 上确实存在上面的问题

**Comment by tomoya92** [comment]
对。有这个问题，还有一个问题，我用了 `--css sass` 生成的文件里有 public/stylesheets/style.sass 这个文件，但app.js里没有做处理

```
//这是express-generator里生成的代码，放到koa项目里没用
app.use(require('node-sass-middleware')({
	src: __dirname + '/public',
	dest: __dirname + '/public',
	indentedSyntax: true,
	sourceMap: true,
	outputStyle: 'compressed'
}));
```

因为没有解析，所以访问 localhost:3000 会出现css 404错误

```
--> GET /stylesheets/style.css 404 2ms -
```

**Comment by i5ting** [comment]
@glennWang 生成ejs有啥问题吗？

**Comment by i5ting** [comment]
@tomoya92 一直没有找到很好的中间件，能否提供一个

**Comment by tomoya92** [comment]
@i5ting 
https://www.npmjs.com/package/koa2-sass
https://www.npmjs.com/package/koa-sass

**Comment by tomoya92** [comment]
@i5ting 
生成ejs就是这个问题 还带着jade的后缀配置信息
```
app.use(views(__dirname + '/views', {
  extension: 'jade' //这里不应该是ejs吗？
}));
```

**Comment by i5ting** [comment]
@tomoya92 你试试最新版本，已经搞定了

**Comment by tomoya92** [comment]
@i5ting 
后缀的问题解决了，但sass的问题还是没有解决

**Comment by i5ting** [comment]
@tomoya92 来呀来呀，一起嗨

**Comment by tomoya92** [comment]
@i5ting 
我要是会弄，就提pr了 😂

**Comment by i5ting** [comment]
@tomoya92 先写demo，然后再来整合到koa-generator，没有谁天生就会的，加油

**Comment by glennWang** [comment]
感谢
