### ISSUE TITLE
npm  start 报错

### ISSUE THREAD

**Issue by xumjs8623** [17koa/koa-generator#38]
mac系统下， npm install 后 npm start 启动项目报错
![image](https://cloud.githubusercontent.com/assets/12467615/24576104/41201c7c-16e8-11e7-8064-c7d66f2083f3.png)

**Comment by tyuexingzhe** [comment]
您好，这个问题怎么解决的啊？我第一次是成功的，删除重新建一个项目就报这个错误

**Comment by xumjs8623** [comment]
@tyuexingzhe   我是因为nodejs版本太低，用async await语法 要高于nodejs 7.6版本
