### ISSUE TITLE
hi.狼哥..jade官方早已建议迁移到pug上了.

### ISSUE THREAD

**Issue by ench44** [17koa/koa-generator#39]
终于看到这个更新东西了. 我每次-g安装这个脚手架工具. 都要自己去手动修改一下koa2 这个文件. 能不能把jade去掉...直接替换成pug呢.

**Comment by i5ting** [comment]
收到

**Comment by i5ting** [comment]
使用https://github.com/i5ting/rfe来重名jade去pug

**Comment by i5ting** [comment]
koa2 已经默认使用pug了，v1.1.11+， koa 1.x下的koa命令还是jade，貌似是koa-views老版本的问题
