### ISSUE TITLE
生成的工程跑不起来，还需要配置别的吗？

### ISSUE THREAD

**Issue by houyaowei** [17koa/koa-generator#41]
![image](https://cloud.githubusercontent.com/assets/3080429/25733134/b40aaeae-3188-11e7-828c-4c4368d07d81.png)

**Comment by i5ting** [comment]
你的node版本太低了，7.6以上才可以使用async函数，你可以使用koa1的生产

**Comment by houyaowei** [comment]
@i5ting ,多谢

**Comment by i5ting** [comment]
@houyaowei 现在koa2主推async函数，所以koa-generator也会这样做的，你可以把中间件改成别的方式
