### ISSUE TITLE
package.json的一点小问题

### ISSUE THREAD

**Issue by pecopeco** [17koa/koa-generator#46]
"start": "node bin/www"应是 "start": "nodemon bin/www"吧?

**Comment by Chan-Chun** [comment]
没有关系啊。就node直接起服务也可以啊

**Comment by pecopeco** [comment]
@Chan-Chun  node直接起服务没有自动重启

**Comment by Chan-Chun** [comment]
@pecopeco 是啊 nodemon就有一个自动重启的服务，node 使用原生的所以没有。package.json自己增加script就好了嘛。想用什么都行 nodemon也可以 pm2也可以。

**Comment by i5ting** [comment]
这个还是自己改吧，如果你全局没有nodemon，程序就没法跑起来了，感谢 @Chan-Chun
