### ISSUE TITLE
请问为什么app.js里面的语句都没有;为结尾

### ISSUE THREAD

**Issue by horsefaced** [17koa/koa-generator#47]
在自动处理成的app.js里, 所有的语句都没有以;为结尾, 这是特别设计的吗?
<img width="479" alt="2017-08-24 16 24 28" src="https://user-images.githubusercontent.com/953648/29657002-d8d25b4e-88e8-11e7-83d4-32e247b12997.png">

**Comment by i5ting** [comment]
standardjs约定的，默认都没有分号，这也是现在流行的写法

**Comment by horsefaced** [comment]
谢谢
