### ISSUE TITLE
无法创建项目

### ISSUE THREAD

**Issue by YangGoldDragon** [17koa/koa-generator#54]
系统: win10   node.js版本：v8.x.x
安装完koa-generator之后，无法创建项目，提示koa2：command not found,尝试重置过系统环境变量也没用，我应该如何排错？

**Comment by roland-dev** [comment]
一般是环节变量问题。
你可以检查一下你的koa-generator的安装目录是否在你的环境变量里面，如果不在把这个目录添加到环境变量里面即可。
![image](https://user-images.githubusercontent.com/44826417/54506453-78e94480-4977-11e9-9833-0b0ee778e098.png)

**Comment by YangGoldDragon** [comment]
It's too late, I have already fix it, anyway, tks
